model_params:
  name: 'VAE1d'
  in_dims: 16
  latent_dim: 8


data_params:
  train_batch_size: 64
  val_batch_size:  64
  num_workers: 4
  data_dim: 16


exp_params:
  LR: 0.005  # 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025  # 0.00025
  manual_seed: 77

trainer_params:
  gpus: [0]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VAE1d"