model_params:
  name: 'VAEConv1d'
  in_channels: 1  # 16
  latent_dim: 8  # 8
  hidden_channels: [64, 32]  # [64, 32]


data_params:
  train_batch_size: 64  # 64
  val_batch_size:  64
  num_workers: 4
  data_dim: 16  # 16, should be the same as hidden_dims


exp_params:
  LR: 0.005  # 0.005
  weight_decay: 0.0  # 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025  # 0.00025
  manual_seed: 77  # 77

trainer_params:
  gpus: [0]
  max_epochs: 500

logging_params:
  save_dir: "logs/"
  name: "VAE1d"