model_params:
  name: 'VAE1d'
  in_dims: 64  # 16, 64
  latent_dim: 64  # 8, 64
  hidden_dims: [256, 128]  # [32, 16], [256, 128]

data_params:
  train_batch_size: 4096  # 64, 5012, 4096
  val_batch_size:  4096  # 64, 5012, 4096
  num_workers: 4
  data_dim: 64  # 16, 64 should be the same as hidden_dims
  data_num: 220000 # 400000, 98000, 180000, 10000000
  data_distribution: "cr3bp_earth_local_optimal"  # "cr3bp_earth_local_optimal", "cr3bp_earth_local_optimal_augmented"
  data_dir: ["/home/anjian/Desktop/project/PyTorch-VAE/Data/cr3bp_earth/della_default_local_optimal_solution"]
  data_output_file_name: "/home/anjian/Desktop/project/global_optimization/pydylan-wrapper/result/solution/from_della/default_local_optimal_47k_mass_415.pickle"
  data_min_max_file_name: "/home/anjian/Desktop/project/global_optimization/pydylan-wrapper/result/solution/from_della/default_local_optimal_47k_mass_415_min_max.pickle"

exp_params:
  LR: 0.001  # 0.005, 0.001
  weight_decay: 0.0  # 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025  # 0.00025
  manual_seed: 77  # 77

trainer_params:
  gpus: [0]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VAE1d_cr3bp_earth"